name: panda_flutter_ui
description: Custom Panda UI components for Flutter's project.
version: 0.0.5
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: 1.1.6
  flutter_spinkit: 5.0.0
  number_display: 3.0.0
  cached_network_image: 3.1.0
  photo_view: 0.13.0
  auto_size_text: 3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: